#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "build.h"
#include "utils.h"
#include "markdown.h"
#include "template.h"

// Sample content for init command
static const char *SAMPLE_INDEX_MD = 
"---\n"
"title: Welcome\n"
"layout: default\n"
"---\n"
"\n"
"# Hello World!\n"
"\n"
"This is a sample page generated by XO-C.\n";

static const char *SAMPLE_LAYOUT =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <title>{{title}}</title>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"</head>\n"
"<body>\n"
"  <header>\n"
"    <h1>XO-C Site</h1>\n"
"  </header>\n"
"  <main>\n"
"    {{{content}}}\n"
"  </main>\n"
"  <footer>\n"
"    <p>Built with XO-C</p>\n"
"  </footer>\n"
"</body>\n"
"</html>";

static const char *SAMPLE_PARTIAL =
"## This is a partial\n"
"\n"
"You can include this in other markdown files using the `{{> partial}}` syntax.\n";

// Initialize a sample project
int xo_init_project(const xo_config_t *config) {
    int result;
    
    // Create content directory
    if ((result = xo_utils_mkdir_p(config->content_dir)) != 0) {
        xo_utils_console_error("Failed to create content directory");
        return result;
    }
    
    // Create layouts directory
    if ((result = xo_utils_mkdir_p(config->layouts_dir)) != 0) {
        xo_utils_console_error("Failed to create layouts directory");
        return result;
    }
    
    // Create partials directory
    char *partials_dir = xo_utils_join_path(config->content_dir, "_partials");
    if (!partials_dir) {
        xo_utils_console_error("Memory allocation failed");
        return XO_ERROR_MEMORY_ALLOCATION;
    }
    
    if ((result = xo_utils_mkdir_p(partials_dir)) != 0) {
        xo_utils_console_error("Failed to create partials directory");
        free(partials_dir);
        return result;
    }
    
    // Create sample index.md
    char *index_path = xo_utils_join_path(config->content_dir, "index.md");
    if (!index_path) {
        xo_utils_console_error("Memory allocation failed");
        free(partials_dir);
        return XO_ERROR_MEMORY_ALLOCATION;
    }
    
    if ((result = xo_utils_write_file(index_path, SAMPLE_INDEX_MD)) != 0) {
        xo_utils_console_error("Failed to write sample index.md");
        free(partials_dir);
        free(index_path);
        return result;
    }
    
    free(index_path);
    
    // Create sample layout
    char *layout_path = xo_utils_join_path(config->layouts_dir, "default.html");
    if (!layout_path) {
        xo_utils_console_error("Memory allocation failed");
        free(partials_dir);
        return XO_ERROR_MEMORY_ALLOCATION;
    }
    
    if ((result = xo_utils_write_file(layout_path, SAMPLE_LAYOUT)) != 0) {
        xo_utils_console_error("Failed to write sample layout");
        free(partials_dir);
        free(layout_path);
        return result;
    }
    
    free(layout_path);
    
    // Create sample partial
    char *partial_path = xo_utils_join_path(partials_dir, "partial.md");
    if (!partial_path) {
        xo_utils_console_error("Memory allocation failed");
        free(partials_dir);
        return XO_ERROR_MEMORY_ALLOCATION;
    }
    
    if ((result = xo_utils_write_file(partial_path, SAMPLE_PARTIAL)) != 0) {
        xo_utils_console_error("Failed to write sample partial");
        free(partials_dir);
        free(partial_path);
        return result;
    }
    
    free(partial_path);
    free(partials_dir);
    
    return XO_SUCCESS;
}

// Placeholder for the build function
int xo_build(const xo_config_t *config) {
    // For now, just create the output directory
    int result = xo_utils_mkdir_p(config->output_dir);
    if (result != 0) {
        xo_utils_console_error("Failed to create output directory");
        return result;
    }
    
    xo_utils_console_info("Build functionality not fully implemented yet");
    return XO_SUCCESS;
}

// Placeholder for the dev server function
int xo_dev_server(const xo_config_t *config) {
    xo_utils_console_info("Development server not implemented yet");
    return XO_SUCCESS;
} 